# Generated by Django 3.0.6 on 2020-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
